import Link from "next/link";
import { Panel, PortalShell } from "../components/portal-shell";

const EVENTS = ["lead.created", "lead.reviewed", "lead.available", "lead.purchased", "lead.delivered", "lead.status_updated", "lead.note_added", "lead.followup_set", "lead.appointment_created", "lead.dnc_marked", "lead.optout_reported", "agent.approved", "agent.compliance_acknowledged", "payment.completed", "payment.failed", "dispute.opened", "privacy_request.opened"];

export default function DeveloperPortal() { return <PortalShell role="developer" eyebrow="Developer tools" title="Valor Legacies API" description="Operational API, consent, webhook, and payload guidance for authorized integrations."><div className="grid gap-5 xl:grid-cols-2">
  <Panel title="API overview"><p className="text-sm leading-6 text-[#8a8175]">The agent API accepts consented lead submissions and protects operational routes with server-validated credentials. Request access rather than embedding credentials in browser code.</p><Link href="/developers/agents" className="mt-4 inline-flex rounded-lg bg-[#176b65] px-4 py-2 text-sm font-semibold text-white">Read API documentation</Link></Panel>
  <Panel title="Authentication"><ul className="list-disc space-y-2 pl-5 text-sm leading-6 text-[#8a8175]"><li>Use a server-side Bearer credential issued by Valor Legacies.</li><li>Never expose API keys in client bundles, query strings, payload previews, or logs.</li><li>Credentials are scoped operationally and may be rotated or revoked.</li></ul></Panel>
  <Panel title="Consent flow"><p className="text-sm leading-6 text-[#8a8175]">Obtain a consent token, have the person confirm it, then submit the lead within the confirmed scope. Consent evidence is required; integrations must not manufacture or broaden consent.</p></Panel>
  <Panel title="Payload principles"><ul className="list-disc space-y-2 pl-5 text-sm leading-6 text-[#8a8175]"><li>Collect only fields required for the requested insurance-guidance purpose.</li><li>Redact contact data, birth dates, consent evidence, tokens, and payment details from operational logs.</li><li>Honor DNC, opt-out, privacy, retention, and deletion controls downstream.</li></ul></Panel>
  <div id="webhooks" className="xl:col-span-2"><Panel title="Operational events"><div className="flex flex-wrap gap-2">{EVENTS.map((event) => <code key={event} className="rounded-lg border border-[#e2d9c9] bg-[#faf8f3] px-2 py-1 text-xs">{event}</code>)}</div><p className="mt-4 text-sm leading-6 text-[#8a8175]"><strong>Current delivery:</strong> signed <code>lead.created</code> webhooks are implemented when server-side target and signing configuration are present. Durable attempt logs and the remaining event deliveries are planned; this vocabulary does not claim they currently execute.</p></Panel></div>
  <div id="support" className="xl:col-span-2"><Panel title="Integration support"><p className="text-sm text-[#8a8175]">Request access or report an integration issue without sending secrets or lead PII.</p><a href="mailto:valorlegacies@gmail.com?subject=Valor%20Legacies%20API%20Support" className="mt-4 inline-flex text-sm font-semibold text-[#176b65]">Contact integration support →</a></Panel></div>
</div></PortalShell>; }
