"use client";

import { useCallback, useEffect, useState } from "react";
import { Panel, PortalShell } from "../../components/portal-shell";

function isValidEmail(email: string) { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()); }

export default function NotificationsPage() {
  const [recipients, setRecipients] = useState<string[]>([]); const [envEmails, setEnvEmails] = useState<string[]>([]);
  const [smtpConfigured, setSmtpConfigured] = useState(true); const [loading, setLoading] = useState(true);
  const [draft, setDraft] = useState(""); const [dirty, setDirty] = useState(false); const [saving, setSaving] = useState(false);
  const [testing, setTesting] = useState(false); const [flash, setFlash] = useState<{ ok: boolean; message: string } | null>(null);
  const load = useCallback(async () => { try { const res = await fetch("/api/admin/notifications", { cache: "no-store" }); if (res.status === 401) { location.href = "/admin/login"; return; } if (res.ok) { const data = await res.json(); setRecipients(data.recipients ?? []); setEnvEmails(data.envAdminEmails ?? []); setSmtpConfigured(Boolean(data.smtpConfigured)); } } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  function addDraft() { const email = draft.trim().toLowerCase(); if (!isValidEmail(email)) return setFlash({ ok: false, message: `“${draft}” is not a valid email.` }); if (recipients.includes(email)) return setFlash({ ok: false, message: `${email} is already listed.` }); setRecipients((items) => [...items, email]); setDraft(""); setDirty(true); setFlash(null); }
  async function save() { setSaving(true); setFlash(null); try { const res = await fetch("/api/admin/notifications", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recipients }) }); const data = await res.json(); if (res.ok && data.success) { setRecipients(data.recipients ?? []); setDirty(false); setFlash({ ok: true, message: "Notification recipients saved." }); } else setFlash({ ok: false, message: data.message || "Save failed." }); } finally { setSaving(false); } }
  async function sendTest() { setTesting(true); setFlash(null); try { const res = await fetch("/api/admin/notifications", { method: "POST" }); const data = await res.json(); setFlash(res.ok && data.success ? { ok: true, message: `Test processed for ${data.sent} recipient(s)${data.failed ? `; ${data.failed} failed` : ""}.` } : { ok: false, message: data.message || "Test failed." }); } finally { setTesting(false); } }
  return <PortalShell role="admin" eyebrow="Operations" title="Notifications" description="Manage real new-lead notification recipients and inspect provider readiness. In-app notification persistence is not enabled yet.">
    {flash && <p className={`mb-4 rounded-xl border p-3 text-sm ${flash.ok ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-red-200 bg-red-50 text-red-700"}`}>{flash.message}</p>}
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel title="New-lead email recipients">{loading ? <p className="text-sm text-[#8a8175]">Loading recipients…</p> : <><div className="flex flex-col gap-2 sm:flex-row"><input type="email" value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addDraft(); } }} placeholder="name@example.com" className="min-w-0 flex-1 rounded-lg border border-[#e2d9c9] px-3 py-2 text-sm"/><button onClick={addDraft} className="rounded-lg bg-[#176b65] px-4 py-2 text-sm font-semibold text-white">Add recipient</button></div><div className="mt-4 divide-y divide-[#e2d9c9] rounded-xl border border-[#e2d9c9]">{recipients.length ? recipients.map((email) => <div key={email} className="flex items-center justify-between gap-3 px-4 py-3"><span className="min-w-0 truncate text-sm">{email}</span><button onClick={() => { setRecipients((items) => items.filter((item) => item !== email)); setDirty(true); }} className="text-xs font-semibold text-red-700">Remove</button></div>) : <p className="p-5 text-sm text-[#8a8175]">No managed recipients yet.</p>}</div><div className="mt-4 flex flex-wrap gap-2"><button onClick={save} disabled={saving || !dirty} className="rounded-lg bg-[#176b65] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving…" : dirty ? "Save changes" : "Saved"}</button><button onClick={sendTest} disabled={testing || !smtpConfigured} className="rounded-lg border border-[#e2d9c9] px-4 py-2 text-sm font-semibold disabled:opacity-50">{testing ? "Sending…" : "Send test email"}</button></div></>}</Panel>
      <div className="space-y-5"><Panel title="Provider status"><p className={`text-sm font-semibold ${smtpConfigured ? "text-emerald-700" : "text-amber-800"}`}>{smtpConfigured ? "Email provider configured" : "Configuration required"}</p><p className="mt-3 text-sm leading-6 text-[#8a8175]">{smtpConfigured ? "The existing transactional email path can process a test." : "Email sending is not configured. SMTP credentials must remain server-side."}</p></Panel><Panel title="Environment recipients">{envEmails.length ? <ul className="space-y-2">{envEmails.map((email) => <li key={email} className="break-all text-sm">{email}</li>)}</ul> : <p className="text-sm text-[#8a8175]">No environment-managed admin recipients.</p>}<p className="mt-3 text-xs text-[#8a8175]">Read-only and never exposes credentials.</p></Panel><Panel title="In-app alerts"><p className="text-sm leading-6 text-[#8a8175]">No persisted admin alert inbox or unread count exists yet. Webhook health and workflow configuration are available on their dedicated pages.</p></Panel></div>
    </div>
  </PortalShell>;
}
