'use strict';
// @oracle-infrastructure — bounded internal-state writes to internally-constructed paths (ledger/queue/config/cache persistence, validation temp-scratch, CI output, self-created sandbox scaffolding, auto-heal writeback) — not user-input-driven mutations

/**
 * Codex Ingest — drains the lexicon-proposals queue into the periodic table.
 *
 * Reads .remembrance/lexicon-proposals.json, filters kind='element' +
 * status='active', and generates src/atomic/periodic-table-additions.js with
 * registerElement({ name, atomicProperties, source }) calls.
 *
 * The GHA workflow commits the change on a branch and opens a PR. No more
 * stale queue that nobody consumes. Auto-merge rule (from sweep) picks it up
 * when the additions file changes ≤ 1 file with all checks green.
 */

const fs = require('fs');
const path = require('path');
const { getActiveElements } = require('./lexicon-integrator');

const ADDITIONS_FILE = path.join(process.cwd(), 'src', 'atomic', 'periodic-table-additions.js');

function renderElement(el) {
  const p = el.atomicProperties || {};
  const props = Object.entries(p).map(([k, v]) => {
    if (typeof v === 'string') return `  ${k}: '${v}'`;
    if (typeof v === 'number') return `  ${k}: ${v}`;
    return `  ${k}: ${JSON.stringify(v)}`;
  }).join(',\n');
  return `registerElement({\n  name: '${el.name}',\n  source: '${el.source}',\n  approvedAt: '${el.approvedAt || ''}',\n${props ? props + ',\n' : ''}});`;
}

function renderFile(elements) {
  // ./element-growth, not ./periodic-table — the door was generated against
  // a name periodic-table never defined, so the first active proposal would
  // have thrown at require time. It now has a real home.
  const header = `'use strict';\n\n// AUTO-GENERATED by codex-ingest. Do not edit by hand.\n// Source: .remembrance/lexicon-proposals.json (kind=element, status=active)\n// Generated: ${new Date().toISOString()}\n// Element count: ${elements.length}\n\nconst { registerElement } = require('./element-growth');\n\n`;
  if (elements.length === 0) {
    return header + '// No active element proposals to ingest.\n\nmodule.exports = { ingested: 0, generatedAt: new Date().toISOString() };\n';
  }
  return header + elements.map(renderElement).join('\n\n') + `\n\nmodule.exports = { ingested: ${elements.length}, generatedAt: new Date().toISOString() };\n`;
}
renderFile.atomicProperties = { charge: 1, valence: 1, mass: "light", spin: "odd", phase: "gas", reactivity: "inert", electronegativity: 0.33, group: 3, period: 2, harmPotential: "none", alignment: "neutral", intention: "neutral", domain: "utility" };

function runIngest(opts = {}) {
  const elements = getActiveElements();
  const seen = new Set();
  const unique = [];
  for (const e of elements) {
    const key = `${e.name}:${e.source}`;
    if (seen.has(key)) continue;
    seen.add(key);
    unique.push(e);
  }
  const content = renderFile(unique);
  const dir = path.dirname(ADDITIONS_FILE);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  let prior = null;
  if (fs.existsSync(ADDITIONS_FILE)) prior = fs.readFileSync(ADDITIONS_FILE, 'utf-8');
  if (prior === content) return { changed: false, reason: 'no new elements', count: unique.length };
  if (!opts.dryRun) fs.writeFileSync(ADDITIONS_FILE, content);
  return { changed: true, count: unique.length, file: ADDITIONS_FILE };
}
runIngest.atomicProperties = { charge: 1, valence: 0, mass: "medium", spin: "odd", phase: "gas", reactivity: "high", electronegativity: 0, group: 6, period: 3, harmPotential: "minimal", alignment: "neutral", intention: "neutral", domain: "utility" };

if (require.main === module) {
  const result = runIngest();
  console.log(JSON.stringify(result, null, 2));
  process.exit(0);
}

module.exports = { runIngest, renderFile, renderElement, ADDITIONS_FILE };

// ── Periodic-table declarations (covenant fractal, atomic scale) ──
// Each element's 13-dimension atomic identity, computed by the substrate's
// own extractAtomicProperties over the function body.
renderElement.atomicProperties = { charge: 0, valence: 0, mass: "medium", spin: "even", phase: "gas", reactivity: "inert", electronegativity: 0, group: 3, period: 2, harmPotential: "none", alignment: "neutral", intention: "neutral", domain: "utility" };
