"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { MetricCard, Panel, PortalShell } from "../../components/portal-shell";

type Lead={leadId:string;firstName:string;lastName:string;email:string;phone:string;consentTcpa:boolean;consentPrivacy:boolean;consentTimestamp:string;consentText:string;consentPageUrl:string;utmSource:string|null;utmCampaign:string|null;createdAt:string;operations:{status:string;doNotContact:boolean;disputeStatus:string|null}};
type Agent={clientId:string;contactName:string;status:string;stateLicenses:string};
type Suppression={id:number;kind:string;valueMasked:string;reason:string;source:string;active:boolean;createdBy:string;createdAt:string};
type Privacy={id:number;leadId:string|null;requester:string;requestType:string;status:string;targetDate:string|null;assignedAdmin:string|null;notes:string;createdAt:string};
type Audit={id:number;createdAt:string;actorId:string;actorRole:string;eventType:string;targetType:string;targetId:string;summary:string};
type Data={leads:Lead[];agents:Agent[];suppressions:Suppression[];privacyRequests:Privacy[];audit:Audit[];acknowledgements:Array<{agentId:string;acknowledgedAt:string}>;reviewedLeadIds:string[]};
const th="px-3 py-2 text-left text-[10px] font-bold uppercase tracking-wide text-[#776e61]";const td="border-t border-[#eee7da] px-3 py-3 text-xs align-top";
export default function ComplianceCenter(){const[data,setData]=useState<Data|null>(null);const[error,setError]=useState("");const[query,setQuery]=useState("");const load=()=>fetch("/api/admin/compliance",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message);setData(d)}).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
const leads=data?.leads??[];const missing=leads.filter(l=>!l.consentTimestamp||!l.consentText||!l.consentTcpa||!l.consentPrivacy);const dnc=leads.filter(l=>l.operations.doNotContact);const openPrivacy=(data?.privacyRequests??[]).filter(r=>!["completed","denied","canceled"].includes(r.status));const acked=new Set((data?.acknowledgements??[]).map(a=>a.agentId));const pendingAgents=(data?.agents??[]).filter(a=>a.status==="active"&&!acked.has(a.clientId));const flags=useMemo(()=>leads.flatMap(l=>[{on:!l.consentTimestamp,label:"Missing consent timestamp"},{on:!l.consentText,label:"Missing disclosure snapshot"},{on:!l.consentPageUrl,label:"Missing source page"},{on:l.operations.doNotContact,label:"Do Not Contact"},{on:!!l.operations.disputeStatus,label:"Lead disputed"}].filter(f=>f.on).map(f=>({...f,leadId:l.leadId,name:`${l.firstName} ${l.lastName}`}))),[leads]);const visible=leads.filter(l=>`${l.leadId} ${l.firstName} ${l.lastName} ${l.utmSource}`.toLowerCase().includes(query.toLowerCase()));
async function action(body:Record<string,unknown>){setError("");const r=await fetch("/api/admin/compliance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setError(d.message);return}load()}
return <PortalShell role="admin" eyebrow="Privacy-minded operations" title="Compliance Center" description="Review consent records, respect opt-outs, manage privacy requests, and keep sensitive actions accountable without replacing professional legal review.">
{error&&<p className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Consent records reviewed" value={data?.reviewedLeadIds.length??"—"} note="Explicit admin reviews"/><MetricCard label="Leads missing consent data" value={data?missing.length:"—"} note="Action needed" urgent={missing.length>0}/><MetricCard label="Active do-not-contact records" value={data?dnc.length:"—"} note="Contact actions restricted"/><MetricCard label="Open privacy requests" value={data?openPrivacy.length:"—"} note="Manual review workflow" urgent={openPrivacy.length>0}/><MetricCard label="Open compliance flags" value={data?flags.length:"—"} note="Computed from live records" urgent={flags.length>0}/><MetricCard label="Acknowledgements pending" value={data?pendingAgents.length:"—"} note="Active agent accounts"/><MetricCard label="Suppressed phone/email" value={data?data.suppressions.filter(s=>s.active).length:"—"} note="Active suppression records"/><MetricCard label="Recent sensitive actions" value={data?data.audit.length:"—"} note="Latest 100 audit events"/></div>
<div className="mt-5 grid gap-5"><Panel title="Compliance Attention Queue">{flags.length?<div className="divide-y divide-[#eee7da]">{flags.slice(0,30).map((f,i)=><div key={`${f.leadId}-${i}`} className="flex items-center justify-between gap-3 py-3 text-sm"><span><strong>{f.label}</strong><span className="ml-2 text-[#8a8175]">{f.name} · {f.leadId}</span></span><Link className="text-[#176b65]" href={`/admin/leads/${f.leadId}`}>Review →</Link></div>)}</div>:<Empty text="No compliance attention items are present in the loaded records."/>}</Panel>
<Panel title="Consent Records" action={<input aria-label="Search consent records" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search lead or source" className="rounded-lg border border-[#e2d9c9] px-3 py-2 text-xs"/>}><Table headers={["Lead / consumer","Consent","Timestamp","Disclosure","Source / campaign","Status","Action"]}>{visible.map(l=><tr key={l.leadId}><td className={td}>{l.firstName} {l.lastName}<small className="block text-[#8a8175]">{l.leadId}</small></td><td className={td}>{l.consentTcpa&&l.consentPrivacy?"Recorded":"Review required"}</td><td className={td}>{date(l.consentTimestamp)}</td><td className={td}>{l.consentText?"Snapshot stored":"Missing"}</td><td className={td}>{l.consentPageUrl||"—"}<small className="block">{l.utmSource||"Direct"} · {l.utmCampaign||"No campaign"}</small></td><td className={td}>{l.operations.status}</td><td className={td}><Link href={`/admin/leads/${l.leadId}`} className="text-[#176b65]">View details</Link></td></tr>)}</Table></Panel>
<Panel title="Do-Not-Contact / Opt-Out Queue">{dnc.length?<Table headers={["Consumer","Contact","Date received","Status","Source lead","Action"]}>{dnc.map(l=><tr key={l.leadId}><td className={td}>{l.firstName} {l.lastName}</td><td className={td}>{mask(l.phone)} · {mask(l.email)}</td><td className={td}>{date(l.createdAt)}</td><td className={td}>Do Not Contact</td><td className={td}>{l.leadId}</td><td className={td}><Link href={`/admin/leads/${l.leadId}`} className="text-[#176b65]">View</Link></td></tr>)}</Table>:<Empty text="No active Do Not Contact records are present."/>}</Panel>
<Panel title="Suppression List" action={<button onClick={()=>{const kind=prompt("phone or email?");const value=prompt("Contact value to suppress");if((kind==="phone"||kind==="email")&&value)action({action:"suppress",kind,value,reason:"Admin suppression",source:"Compliance Center"})}} className="rounded-lg bg-[#176b65] px-3 py-2 text-xs font-bold text-white">Add suppression</button>}><Table headers={["Type","Masked value","Reason","Created","Created by","Source","Status"]}>{(data?.suppressions??[]).map(s=><tr key={s.id}><td className={td}>{s.kind}</td><td className={td}>{s.valueMasked}</td><td className={td}>{s.reason}</td><td className={td}>{date(s.createdAt)}</td><td className={td}>{s.createdBy}</td><td className={td}>{s.source}</td><td className={td}>{s.active?"Active":"Inactive"}</td></tr>)}</Table></Panel>
<Panel title="Privacy Requests" action={<button onClick={()=>{const requester=prompt("Requester name or masked identifier");const requestType=prompt("Type: access, deletion, correction, opt-out, data-sharing-inquiry, other");if(requester&&requestType)action({action:"privacy",requester,requestType})}} className="rounded-lg bg-[#176b65] px-3 py-2 text-xs font-bold text-white">Create request</button>}><p className="mb-4 text-xs text-[#8a8175]">Deletion requests require manual review before deletion.</p><Table headers={["Requester","Type","Received","Target","Status","Assigned","Notes / action"]}>{(data?.privacyRequests??[]).map(r=><tr key={r.id}><td className={td}>{r.requester}<small className="block">{r.leadId||"Unlinked"}</small></td><td className={td}>{r.requestType}</td><td className={td}>{date(r.createdAt)}</td><td className={td}>{date(r.targetDate)}</td><td className={td}>{r.status}</td><td className={td}>{r.assignedAdmin||"Unassigned"}</td><td className={td}>{r.notes||"—"}<button onClick={()=>action({action:"privacy-update",id:r.id,status:"completed",notes:r.notes,assignedAdmin:r.assignedAdmin})} className="mt-1 block text-[#176b65]">Mark completed</button></td></tr>)}</Table></Panel>
<Panel title="Agent Compliance"><Table headers={["Agent","License states","Acknowledgement","Last acknowledgement","Purchase eligibility","Action"]}>{(data?.agents??[]).map(a=>{const ack=data?.acknowledgements.find(x=>x.agentId===a.clientId);return <tr key={a.clientId}><td className={td}>{a.contactName}</td><td className={td}>{a.stateLicenses||"Not supplied"}</td><td className={td}>{ack?"Current":"Pending"}</td><td className={td}>{date(ack?.acknowledgedAt)}</td><td className={td}>{a.status==="active"&&ack?"Eligible":"Review required"}</td><td className={td}><Link href="/admin/clients" className="text-[#176b65]">View agent</Link></td></tr>})}</Table></Panel></div></PortalShell>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px]"><thead><tr>{headers.map(h=><th key={h} className={th}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>};function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed border-[#d9cfbd] bg-[#faf8f3] p-5 text-sm text-[#776e61]">{text}</p>};function date(v?:string|null){return v?new Date(v).toLocaleString():"—"}function mask(v:string){return v.includes("@")?`${v.slice(0,2)}•••@${v.split("@")[1]}`:`•••${v.replace(/\D/g,"").slice(-4)}`}
