"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { MetricCard, Panel, PortalShell } from "../../components/portal-shell";
import { trainingModules } from "../../lib/portal-training-content";

export default function AdminTrainingPage(){const router=useRouter();const[ready,setReady]=useState(false);useEffect(()=>{fetch("/api/admin/check",{cache:"no-store"}).then(response=>{if(!response.ok)throw new Error();setReady(true)}).catch(()=>router.replace("/admin/login"))},[router]);if(!ready)return <main className="grid min-h-screen place-items-center bg-[#f4efe5] text-sm text-[#776e61]">Checking admin access…</main>;
  const sensitive=trainingModules.filter(module=>module.complianceSensitive).length;const categories=new Set(trainingModules.map(module=>module.category)).size;
  return <PortalShell role="admin" eyebrow="Agent enablement" title="Training Content Overview" description="Review the published scripts and guardrails agents can use in their lead workflows."><div className="grid gap-3 sm:grid-cols-3"><MetricCard label="Published modules" value={trainingModules.length} note="Static, version-controlled content"/><MetricCard label="Categories" value={categories} note="Searchable in the agent library"/><MetricCard label="Compliance-sensitive" value={sensitive} note="Marked for careful review" urgent={sensitive>0}/></div><div className="mt-5"><Panel title="Published training modules" action={<Link href="/agent/training" className="text-xs font-bold text-[#176b65]">Preview library →</Link>}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-xs uppercase tracking-wide text-[#776e61]"><tr className="border-b border-[#e2d9c9]"><th className="pb-3">Module</th><th className="pb-3">Category</th><th className="pb-3">Status</th><th className="pb-3">Review</th></tr></thead><tbody>{trainingModules.map(module=><tr key={module.slug} className="border-b border-[#eee7db] last:border-0"><td className="py-4"><strong>{module.title}</strong><p className="mt-1 text-xs text-[#8a8175]">{module.tags.join(" · ")}</p></td><td className="py-4 text-[#62594e]">{module.category}</td><td className="py-4"><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">Published</span></td><td className="py-4 text-[#776e61]">{module.complianceSensitive?"Compliance-sensitive":"Standard"}</td></tr>)}</tbody></table></div></Panel></div><p className="mt-4 text-xs leading-5 text-[#8a8175]">Content is read-only and version controlled in Phase 5. No publishing state, completion, favorites, or acknowledgement persistence is implied.</p></PortalShell>}
