import * as React from "react";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import { CookieConsent } from "./components/cookie-consent";
import { ErrorReporter } from "./components/error-reporter";
import { Navbar } from "./components/navbar";
import { SacredGeometryBg } from "./components/sacred-geometry-bg";
import { AnalyticsScripts } from "./components/analytics-scripts";
import { AuthProvider } from "./components/auth-provider";

/** Take the first URL if env var contains comma-separated values. */
const BASE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "https://valorlegacies.com"
)
  .split(",")[0]
  .trim();

const SITE_URL = BASE_URL;
const SITE_TITLE = "Valor Legacies | Life Insurance for Every Chapter of Life";
const SITE_DESCRIPTION =
  "Valor Legacies helps families explore life insurance options for new babies, new homes, marriage, income protection, retirement, final expenses, veterans, and legacy planning.";

export const metadata: Metadata = {
  title: {
    default: SITE_TITLE,
    template: "%s | Valor Legacies",
  },
  description: SITE_DESCRIPTION,
  manifest: "/manifest.json",
  metadataBase: new URL(SITE_URL),
  alternates: {
    canonical: "/",
    types: {
      "application/feed+json": "/feed.json",
    },
  },
  keywords: [
    "life insurance",
    "military life insurance",
    "veteran life insurance",
    "SGLI alternative",
    "term life insurance",
    "whole life insurance",
    "military family coverage",
  ],
  authors: [{ name: "Valor Legacies" }],
  creator: "Valor Legacies",

  // ─── Open Graph ───
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Valor Legacies",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    // OG image auto-generated by app/opengraph-image.tsx (PNG, 1200x630)
  },

  // ─── Twitter / X Cards ───
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    // Twitter image auto-generated by app/opengraph-image.tsx
  },

  // ─── Icons (SVG — universal modern browser support) ───
  icons: {
    icon: [{ url: "/icon.svg", type: "image/svg+xml" }],
    shortcut: "/icon.svg",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#1A1B3A" },
    { media: "(prefers-color-scheme: light)", color: "#F4F3F0" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

// JSON-LD structured data for Google rich results
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      name: "Valor Legacies",
      url: BASE_URL,
      description:
        "Veteran-founded, family-focused resource helping families explore life insurance for major life chapters.",
    },
    {
      "@type": "Organization",
      name: "Valor Legacies",
      url: BASE_URL,
      description:
        "Veteran-founded, independent life insurance resource helping families compare protection options for major life events.",
      contactPoint: {
        "@type": "ContactPoint",
        contactType: "customer service",
        email: "valorlegacies@gmail.com",
        availableLanguage: "English",
      },
      areaServed: { "@type": "Country", name: "United States" },
      sameAs: [
        "https://www.va.gov/life-insurance/",
        "https://www.benefits.va.gov/insurance/",
      ],
      knowsAbout: [
        "Life Insurance",
        "Family Protection",
        "Mortgage Protection",
        "Final Expense Insurance",
        "Income Protection",
        "Legacy Planning",
      ],
    },
    {
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: BASE_URL },
        {
          "@type": "ListItem",
          position: 3,
          name: "Resources",
          item: `${BASE_URL}/resources`,
        },
        {
          "@type": "ListItem",
          position: 4,
          name: "About",
          item: `${BASE_URL}/about`,
        },
        {
          "@type": "ListItem",
          position: 5,
          name: "FAQ",
          item: `${BASE_URL}/faq`,
        },
        {
          "@type": "ListItem",
          position: 6,
          name: "Privacy Policy",
          item: `${BASE_URL}/privacy`,
        },
        {
          "@type": "ListItem",
          position: 7,
          name: "Terms of Service",
          item: `${BASE_URL}/terms`,
        },
      ],
    },
    {
      "@type": "Service",
      name: "Free Life Insurance Coverage Review",
      provider: {
        "@type": "Organization",
        name: "Valor Legacies",
      },
      description:
        "Free, no-obligation life insurance coverage review for families across life's major chapters. Connects consumers with licensed insurance professionals.",
      areaServed: "US",
      audience: {
        "@type": "Audience",
        audienceType:
          "Families, veterans, homeowners, parents, spouses, and legacy planners",
      },
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
        description: "Free coverage review — no cost, no obligation",
      },
    },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="search"
          type="application/opensearchdescription+xml"
          href="/opensearch.xml"
          title="Valor Legacies Search"
        />
        <link
          rel="alternate"
          type="application/feed+json"
          href="/feed.json"
          title="Valor Legacies JSON Feed"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-screen bg-[var(--bg-deep)]">
        <AuthProvider>
          <SacredGeometryBg />
          <Navbar />
          {children}
          <CookieConsent />
          <ErrorReporter />
        </AuthProvider>
        <AnalyticsScripts />
        <script
          dangerouslySetInnerHTML={{
            __html:
              "if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js')",
          }}
        />
      </body>
    </html>
  );
}
