export type TrainingSection = { heading: string; body?: string; bullets?: string[] };
export type TrainingModule = {
  slug: string; title: string; category: string; summary: string; bestUsedWhen: string;
  tags: string[]; scripts: { label: string; text: string }[]; sections: TrainingSection[];
  whyItWorks: string[]; compliance: string[]; related: string[]; complianceSensitive?: boolean;
};

const standardCaution = "Do not promise approval, pricing, benefits, or eligibility before reviewing the client's details and applicable carrier guidelines.";

export const textTemplates = [
  ["First follow-up", "Hi [Name], this is [Agent] with Valor Legacies. I'm following up on your request about [Life Chapter]. I'll keep it simple — my goal is to help you understand what options may fit. Is now still a good time?"],
  ["Missed call", "Hi [Name], this is [Agent] with Valor Legacies. I just tried to reach you about your request. What time works best for a brief review?"],
  ["Appointment confirmation", "Hi [Name], this is [Agent] confirming our simple coverage review for [Appointment Time]. Reply YES to confirm, or let me know if another time is better."],
  ["Appointment reminder", "Hi [Name], a quick reminder from [Agent] about our coverage review at [Appointment Time]. I look forward to speaking with you."],
  ["No-show recovery", "Hi [Name], I missed you at [Appointment Time]. I know schedules change. Would later today or tomorrow be easier for our brief review?"],
  ["After quote sent", "Hi [Name], this is [Agent]. I sent the options we reviewed. What questions can I clarify about the policy terms or next steps?"],
  ["Thinking it over", "Hi [Name], I understand you want time to think. What part would be most helpful to clarify before you decide on a next step?"],
  ["Spouse or payor follow-up", "Hi [Name], this is [Agent]. Would it help to include your spouse or payor in a brief review so everyone can ask questions together?"],
  ["Employer coverage", "Hi [Name], this is [Agent]. Work coverage can be a helpful start. I can help you review how it works and whether personally owned options may fit alongside it."],
  ["Final expense", "Hi [Name], this is [Agent]. I'm following up on your final expense request. My role is to explain options that may help protect your family from those costs."],
  ["Veteran benefits", "Hi [Name], this is [Agent] with Valor Legacies. I can help you review how private coverage may fit alongside benefits you earned. Valor Legacies is not affiliated with the VA, DoD, or any government agency."],
  ["Not ready yet", "Hi [Name], this is [Agent]. No pressure — when the time is right, I can help you review options based on your goals and policy terms. May I check back next month?"],
] as const;

export const voicemailScripts = [
  ["First attempt", "Hi [Name], this is [Agent] with Valor Legacies following up on your request. I'll keep the review simple. Call me at [Phone]. Again, this is [Agent]."],
  ["Second attempt", "Hi [Name], this is [Agent] following up on the guidance you requested. I can help review options that may fit. Please call me at [Phone]."],
  ["Appointment reminder", "Hi [Name], this is [Agent] confirming our coverage review at [Appointment Time]. Call me at [Phone] if your schedule changed."],
  ["Missed appointment", "Hi [Name], this is [Agent]. I missed you for our scheduled review. I understand plans change. Call me at [Phone] to find a better time."],
  ["Final attempt", "Hi [Name], this is [Agent] with Valor Legacies. This is my final follow-up on your request. If you still want guidance, call me at [Phone]."],
] as const;

export const discoveryQuestions: Record<string, string[]> = {
  "New Parents": ["What changed most financially after welcoming your baby?", "If your income stopped unexpectedly, how long would your household be okay?", "Who would help cover childcare, housing, and daily expenses?", "Do you have personally owned coverage outside work?", "What future needs matter most to protect?"],
  Homeowners: ["Would your family want to remain in the home if something happened to you?", "Would you want to pay off the mortgage, cover payments temporarily, or create transition money?", "How many years remain on the mortgage?", "Whose income supports the payment?", "Is your current coverage personally owned or connected to work?"],
  "Newly Married": ["What financial responsibilities do you now share?", "Would either spouse struggle to maintain the household alone?", "Do you have debts the other person could face?", "What protection does each spouse already own?", "What would feeling financially secure look like?"],
  "Protecting Spouse": ["Which expenses depend on your support?", "How long would your spouse need income support?", "Are there debts or caregiving duties to consider?", "What coverage is already in place?", "Who should be involved in the review?"],
  "Protecting Income": ["Who depends on your income each month?", "How long should replacement income last?", "Which bills could not be reduced quickly?", "Do you have emergency savings?", "Is your existing coverage portable?"],
  "Employer Coverage": ["How much coverage is available through work?", "Is it portable if you leave?", "Can it be converted, and under what terms?", "Would it be enough for income replacement?", "Do you own any coverage independently?"],
  "Final Expense": ["Who would handle your final arrangements?", "Have you estimated funeral and related costs?", "Is money already set aside?", "Are there small debts your family might handle?", "What monthly amount feels comfortable to explore?"],
  Retirement: ["Who depends on your retirement income?", "How might the loss of one income affect your spouse?", "Are final costs included in your plan?", "What assets do you want to preserve?", "What coverage do you expect to keep in retirement?"],
  Legacy: ["Who or what would you like your legacy to support?", "Are there assets you want heirs to retain?", "Do you have charitable intentions?", "What existing estate plans should a licensed professional consider?", "How important is predictable protection versus flexibility?"],
  "Veterans & Military Families": ["What military or VA-related coverage do you currently have?", "Have you reviewed SGLI or VGLI terms and deadlines?", "What costs would your family still need to cover?", "Would private coverage portability matter?", "Who depends on your income or care?"],
  "Unsure / General": ["Who or what do you most want protected?", "What prompted the request today?", "What coverage do you already have?", "What monthly responsibilities concern you most?", "Would education or a needs review be the best first step?"],
};

type ObjectionSeed = [string, string, string, string, string, string];
const objections: ObjectionSeed[] = [
  ["I'm not interested.", "They may feel surprised, pressured, or unclear about the request.", "I understand, and I don't want to pressure you.", "Did something change, or is this simply not a good time?", "My role is only to clarify the request and help if the review is useful.", "Would you prefer I close the request or arrange a better time?"],
  ["I already have coverage.", "They may not know whether it is enough, permanent, portable, or personally owned.", "That's good. I'm glad you already have something in place.", "Do you know if it's personally owned or through work?", "My goal isn't to replace what works; it's to help confirm it protects people as intended.", "Would a brief gap review be helpful?"],
  ["I have coverage through work.", "They may assume group coverage follows them or fully replaces income.", "Work coverage is a helpful start.", "Do you know whether it is portable and how much it provides?", "We can review how personally owned coverage may fit alongside it.", "May we check the terms together?"],
  ["I'm too busy.", "They may need control over timing.", "I respect your time.", "Would a ten-minute review at a scheduled time be easier?", "We can keep the first step focused on your priorities.", "Is later today or tomorrow better?"],
  ["I need to think about it.", "They may have an unanswered concern.", "Of course; this deserves thought.", "Which part would be most useful to clarify?", "I can provide facts without asking you to decide today.", "Should we schedule a short question-and-answer follow-up?"],
  ["I need to talk to my spouse.", "They want a shared decision.", "That makes sense; protection affects both of you.", "What questions do you expect your spouse will have?", "A joint review can keep everyone working from the same policy information.", "When could both of you join briefly?"],
  ["I can't afford it.", "They may expect a higher cost or have a firm budget.", "I understand that affordability matters.", "Is there a comfortable range to review without commitment?", "A licensed professional can review options subject to eligibility and carrier guidelines.", "Would you like to see whether any suitable option fits that range?"],
  ["I'm waiting until later.", "They may not see urgency or may have competing priorities.", "I understand wanting to wait.", "What would need to change for the timing to feel right?", "Reviewing now can provide information without requiring a decision.", "May I follow up at a date you choose?"],
  ["I'm young and healthy.", "They may believe protection is only for older people.", "Being young and healthy is a strong place to begin a review.", "Who would be affected if your income or care stopped?", "Eligibility and pricing depend on underwriting and policy terms, so we can only review possibilities.", "Would a simple needs review be useful?"],
  ["The state/Social Security/VA will pay for it.", "They may not know benefit limits or eligibility rules.", "Those benefits may be helpful.", "Have you confirmed the current amount and eligibility directly with the agency?", "Benefits and a complete family plan are not always the same thing.", "Would you like to identify costs that may remain?"],
  ["I've been getting too many calls.", "They may be frustrated and want contact to stop.", "I'm sorry the calls have been frustrating.", "Would you like me to record that you do not want further contact?", "I will respect your contact preference immediately.", "Should I mark this request Do Not Contact now?"],
  ["I don't trust online forms.", "They may be concerned about privacy or who received their information.", "That's a reasonable concern.", "What would help you feel comfortable verifying the request?", "I can explain our role and use only authorized information.", "Would you prefer to review privacy and consent details first?"],
  ["Just send me information.", "They may want a low-pressure starting point.", "Absolutely; I can keep it informational.", "Which question should the information answer?", "Policy details vary, so a little context helps avoid irrelevant material.", "May I ask two brief questions before sending it?"],
  ["I only want the cheapest option.", "They want affordability but may not have defined needed protection.", "Keeping the cost manageable is important.", "What protection must the option accomplish for your family?", "We can review price alongside benefits, exclusions, duration, and suitability.", "What budget and protection goal should we start with?"],
  ["I had a bad experience with insurance before.", "They may need transparency and control.", "I'm sorry that happened, and I understand the caution.", "What part of that experience should we avoid repeating?", "We can move slowly and rely on written carrier and policy terms.", "Would a no-pressure review of your questions be useful?"],
];

export const objectionItems = objections.map(([objection, meaning, acknowledge, ask, align, nextStep]) => ({ objection, meaning, acknowledge, ask, align, nextStep, caution: "Do not make assumptions about existing coverage, eligibility, benefits, price, or outcomes; verify facts and follow contact preferences." }));

export const trainingModules: TrainingModule[] = [
  { slug:"golden-standard-first-call", title:"The Golden Standard First Call", category:"Coverage Basics", summary:"A calm seven-step framework for turning a request into a useful review.", bestUsedWhen:"A new or general-inquiry lead is ready for first contact.", tags:["first-call","golden-standard"], scripts:[{label:"Core opener",text:"Hi [Name], this is [Agent] with Valor Legacies. I'm following up because you requested guidance about life insurance. I'll keep this simple. My job is to understand what changed in your life, what you're trying to protect, and then help you review options that may fit."}], sections:[{heading:"Framework",bullets:["Warm introduction","Confirm the request","Honor their time","Identify the life chapter","Ask the first meaningful question","Explain the next step","Set an expectation for a simple review"]}], whyItWorks:["Confirms context before discovery.","Positions the agent as a guide.","Creates a clear, low-pressure next step."], compliance:[standardCaution], related:["life-chapter-openers","compliance-safe-language"] },
  { slug:"life-chapter-openers", title:"Life-Chapter Openers", category:"New Parents", summary:"Openers and need-gap bridges shaped around the reason a person requested help.", bestUsedWhen:"The lead's life chapter or coverage interest is known.", tags:["first-call","new-parent","mortgage-protection","employer-coverage"], scripts:[{label:"New parent opener",text:"Hi [Name], this is [Agent] with Valor Legacies. I'm following up because you requested guidance after welcoming a new baby. First, congratulations. My job is simple — to help you understand what protection may fit this new chapter and make sure your family has options."},{label:"Homeowner bridge",text:"Your home is more than a mortgage. It's where your family's life is being built. Let's review the income that keeps it secure."},{label:"Spouse and income bridge",text:"Your income supports more than bills. It supports the people who count on you every day."},{label:"Unsure opener",text:"You don't have to know what type of policy you need. That's what the review is for. We'll start with what you want protected and go from there."}], sections:[{heading:"New parent need-gap",body:"A new baby means more than love. It means more people depending on income, care, stability, and a plan."},{heading:"Discovery question bank",bullets:Object.entries(discoveryQuestions).flatMap(([category,questions])=>questions.map(q=>`${category}: ${q}`))}], whyItWorks:["Acknowledges the life event.","Starts with warmth and discovery.","Connects needs to real responsibilities."], compliance:[standardCaution], related:["golden-standard-first-call","discovery-question-bank"] },
  { slug:"text-message-templates", title:"Text Message Templates", category:"Follow-Up", summary:"Short, warm templates for each common follow-up moment.", bestUsedWhen:"The lead has consented to text contact and is not suppressed or Do Not Contact.", tags:["text","follow-up","appointment"], scripts:textTemplates.map(([label,text])=>({label,text})), sections:[{heading:"Use with care",body:"Copy the placeholder template, personalize only inside the authorized lead workspace, and honor opt-outs immediately."}], whyItWorks:["Keeps messages concise.","Explains why the agent is contacting the lead.","Invites a simple response."], compliance:["Confirm consent and suppression status before texting.",standardCaution], related:["appointment-confirmation","no-show-recovery","compliance-safe-language"], complianceSensitive:true },
  { slug:"voicemail-scripts", title:"Voicemail Scripts", category:"Follow-Up", summary:"Five concise voicemails designed to be delivered in under 20 seconds.", bestUsedWhen:"A contact attempt is permitted but the lead does not answer.", tags:["voicemail","follow-up","appointment"], scripts:voicemailScripts.map(([label,text])=>({label,text})), sections:[{heading:"Delivery",body:"Speak clearly, leave one callback number, and avoid sensitive details."}], whyItWorks:["Provides context quickly.","Avoids price or approval claims.","Respects the listener's time."], compliance:["Never leave private health or financial information in voicemail.",standardCaution], related:["text-message-templates","compliance-safe-language"], complianceSensitive:true },
  { slug:"appointment-confirmation", title:"Appointment Confirmation", category:"Follow-Up", summary:"Set a clear time and make rescheduling easy.", bestUsedWhen:"An appointment has been agreed to.", tags:["appointment","text","follow-up"], scripts:[{label:"Confirmation",text:textTemplates[2][1]},{label:"Reminder",text:textTemplates[3][1]}], sections:[], whyItWorks:["Restates the time.","Offers a low-friction response."], compliance:["Send only through an authorized channel and honor opt-outs."], related:["no-show-recovery","text-message-templates"] },
  { slug:"no-show-recovery", title:"No-Show Recovery", category:"Follow-Up", summary:"A respectful reset when schedules change.", bestUsedWhen:"A permitted lead missed a scheduled appointment.", tags:["appointment","follow-up","text"], scripts:[{label:"Recovery text",text:textTemplates[4][1]},{label:"Recovery voicemail",text:voicemailScripts[3][1]}], sections:[], whyItWorks:["Assumes positive intent.","Offers two simple next steps."], compliance:["Stop outreach when requested or suppressed."], related:["appointment-confirmation","text-message-templates"] },
  { slug:"triple-a-objection-handling", title:"Triple-A Objection Handling", category:"Objection Handling", summary:"Acknowledge, Ask, and Align without pressure.", bestUsedWhen:"A client raises a concern or asks to slow down.", tags:["objection","golden-standard"], scripts:objectionItems.map(i=>({label:i.objection,text:`Acknowledge: ${i.acknowledge}\nAsk: ${i.ask}\nAlign: ${i.align}\nNext step: ${i.nextStep}`})), sections:objectionItems.map(i=>({heading:i.objection,bullets:[`What they may mean: ${i.meaning}`,`Acknowledge: ${i.acknowledge}`,`Ask: ${i.ask}`,`Align: ${i.align}`,`Next step: ${i.nextStep}`,`Caution: ${i.caution}`]})), whyItWorks:["Validates before asking.","Finds the concern behind the words.","Aligns the next step with the client's goal."], compliance:["A request to stop is not an objection to overcome. Record it and stop outreach immediately.",standardCaution], related:["compliance-safe-language","golden-standard-first-call"], complianceSensitive:true },
  { slug:"work-coverage-conversations", title:"Work Coverage Conversations", category:"Employer Coverage", summary:"Review group coverage without dismissing it.", bestUsedWhen:"A lead relies on employer-provided life insurance.", tags:["employer-coverage","objection"], scripts:[{label:"Opener",text:"Work coverage is a good start. But your family's protection should not depend only on where you work. May we review whether it is portable and what it provides?"}], sections:[{heading:"Discovery",bullets:discoveryQuestions["Employer Coverage"]}], whyItWorks:["Affirms existing action.","Explores portability and amount.","Avoids assuming a gap."], compliance:["Do not claim employer coverage is insufficient without reviewing its terms."], related:["life-chapter-openers","triple-a-objection-handling"] },
  { slug:"final-expense-conversations", title:"Final Expense Conversations", category:"Final Expense", summary:"Dignity-first language for final-cost planning.", bestUsedWhen:"A lead wants to reduce the burden of final expenses.", tags:["final-expense","first-call"], scripts:[{label:"Dignity bridge",text:"Final expense planning is not about death. It's about love, dignity, and not leaving your family with a bill during one of the hardest moments of their lives."},{label:"Follow-up text",text:textTemplates[9][1]}], sections:[{heading:"Discovery",bullets:discoveryQuestions["Final Expense"]}], whyItWorks:["Centers dignity.","Invites fact-based planning."], compliance:["Government, Social Security, state, military, and VA benefits vary; never promise they will or will not cover a cost."], related:["compliance-safe-language","triple-a-objection-handling"], complianceSensitive:true },
  { slug:"retirement-legacy-conversations", title:"Retirement & Legacy Conversations", category:"Retirement & Legacy", summary:"Careful permanent-coverage language centered on protection and policy terms.", bestUsedWhen:"A lead asks about retirement, permanent insurance, cash value, or legacy goals.", tags:["retirement","legacy","compliance"], scripts:[{label:"Planning bridge",text:"Retirement is not only about how long money lasts. It can also include protecting a spouse, preserving assets, handling final costs, and leaving a legacy, depending on the policy and your circumstances."}], sections:[{heading:"Retirement discovery",bullets:discoveryQuestions.Retirement},{heading:"Legacy discovery",bullets:discoveryQuestions.Legacy}], whyItWorks:["Keeps protection central.","Uses conditional language."], compliance:["Do not promise tax-free retirement income or cash-value growth.","Do not present life insurance as an investment replacement.","Use may, can, depending on the policy, and subject to policy terms."], related:["compliance-safe-language","discovery-question-bank"], complianceSensitive:true },
  { slug:"veteran-benefits-conversations", title:"Veteran Benefits Conversations", category:"Veterans & Military Families", summary:"Respectful benefit-gap conversations without implying government affiliation.", bestUsedWhen:"A veteran or military family wants to understand private coverage alongside earned benefits.", tags:["veteran","first-call","compliance"], scripts:[{label:"Benefits bridge",text:"Your service earned benefits. But benefits and a full protection plan are not always the same thing. May we review SGLI or VGLI and any costs your family would still face?"},{label:"Text follow-up",text:textTemplates[10][1]}], sections:[{heading:"Discovery",bullets:discoveryQuestions["Veterans & Military Families"]},{heading:"Private coverage bridge",body:"Private coverage may help address needs outside military or VA benefits, subject to eligibility, carrier guidelines, and policy terms."}], whyItWorks:["Honors service.","Separates earned benefits from private planning.","Invites verification rather than assumptions."], compliance:["Valor Legacies is not affiliated with the VA, DoD, or any government agency.","Do not characterize agency benefits without current, verified information."], related:["compliance-safe-language","final-expense-conversations"], complianceSensitive:true },
  { slug:"discovery-question-bank", title:"Life-Chapter Discovery Questions", category:"Coverage Basics", summary:"Five practical questions for each of eleven life chapters.", bestUsedWhen:"The agent needs to understand responsibilities and possible protection gaps before discussing options.", tags:["golden-standard","new-parent","mortgage-protection","employer-coverage","retirement","legacy","veteran"], scripts:[], sections:Object.entries(discoveryQuestions).map(([heading,bullets])=>({heading,bullets})), whyItWorks:["Prioritizes listening.","Surfaces existing resources.","Connects needs to the client's own goals."], compliance:["Questions are for a needs conversation, not a promise of product eligibility."], related:["life-chapter-openers","golden-standard-first-call"] },
  { slug:"compliance-safe-language", title:"Compliance-Safe Language", category:"Compliance", summary:"Clear guardrails for accurate, professional conversations.", bestUsedWhen:"Before any outreach, recommendation, benefit discussion, or veteran-family conversation.", tags:["compliance","golden-standard"], scripts:[{label:"Careful language",text:"This option may help, depending on the policy, eligibility, carrier guidelines, and policy terms. A licensed professional can review options with you."}], sections:[{heading:"Use careful language",bullets:["may help","can help","depending on the policy","subject to eligibility","subject to carrier guidelines","based on policy terms","a licensed professional can review options with you"]},{heading:"Avoid",bullets:["guaranteed approval unless accurately describing a specific guaranteed-issue product","guaranteed savings","tax-free retirement as a blanket promise","investment replacement","the government will cover it","VA benefits cover everything","you definitely qualify","your price will never change unless policy terms support it","this is the best policy without suitability context"]}], whyItWorks:["Keeps statements conditional and verifiable.","Protects the client's ability to make an informed choice."], compliance:["Valor Legacies is not affiliated with the VA, DoD, or any government agency.","Honor Do Not Contact and opt-out requests immediately."], related:["golden-standard-first-call","veteran-benefits-conversations"], complianceSensitive:true },
];

export function getTrainingModule(slug: string) { return trainingModules.find(module => module.slug === slug); }

export function getContextualTraining(input: { status: string; coverageInterest?: string; purchaseIntent?: string }) {
  const normalized = `${input.coverageInterest ?? ""} ${input.purchaseIntent ?? ""}`.toLowerCase();
  const moduleSlug = normalized.includes("veteran") || normalized.includes("military") ? "veteran-benefits-conversations" : normalized.includes("final") ? "final-expense-conversations" : normalized.includes("work") || normalized.includes("employer") ? "work-coverage-conversations" : normalized.includes("retire") || normalized.includes("legacy") ? "retirement-legacy-conversations" : normalized.includes("home") || normalized.includes("mortgage") || normalized.includes("baby") || normalized.includes("parent") ? "life-chapter-openers" : "golden-standard-first-call";
  const module = getTrainingModule(moduleSlug)!;
  if (input.status === "Lost") return { module, closed: true, opener: "This lead is closed. Review the record respectfully and do not restart outreach without a new authorized request.", text: "" };
  if (input.status === "Appointment Set") return { module:getTrainingModule("appointment-confirmation")!, opener:"Confirm the agreed appointment and set an expectation for a simple review.", text:textTemplates[2][1] };
  if (input.status === "Follow-Up" || input.status === "Contacted") return { module, opener:`Hi [Name], this is [Agent] with Valor Legacies following up on the coverage guidance you requested. What questions can I clarify before we choose the next useful step?`, text:textTemplates[1][1] };
  return { module, opener:module.scripts[0]?.text ?? getTrainingModule("golden-standard-first-call")!.scripts[0].text, text:textTemplates[0][1] };
}
